plugins { id 'com.android.application' }
android {
    namespace 'io.github.zlm110387.immersiveswitch'
    compileSdk 35
    defaultConfig {
        applicationId 'io.github.zlm110387.immersiveswitch'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
    buildFeatures { aidl true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
